version: 1
accounts:
    - name: alice
      coins: ["1000token", "100000000stake"]
    - name: bob
      coins: ["500token"]
    - name: kyonkopa
      coins: ["10000token", "100000000stake", "1000000000000uphoton"]
validator:
    name: alice
    staked: "100000000stake"
